### ISSUE TITLE
파이어폭스에서 광고차단을 진행해도 광고차단 창이 계속 화면에 보입니다.

### ISSUE THREAD

**Issue by widz4rd** [ajkj/xe-no_adblock_addon#1]
이슈를 이렇게 남기는게 맞는지는 잘 모르겠습니다. 첫 작성이니 이해 부탁드립니다.

현재 테스트해본 브라우저는 스윙브라우저(uBlock), 크롬브라우저(Adblock), 파이어폭스(Adblock Plus) 입니다.

스윙브라우저와 크롬브라우저에서는 정상적으로 해제 후 재접속을 진행하면 팝업창이 뜨지 않습니다.
하지만 파이어폭스에서는 해제해도 계속 뜨는 문제가 있습니다.

개인적인 문제일 수도 있으니 다른분들의 이슈도 등록되면 개발자분께서 한번 검토해보시는것도 좋을거라고 생각됩니다.

좋은 애드온 개발해주셔서 감사합니다. 잘 사용하겠습니다. ;)*

**Comment by ajkj** [comment]
확인결과 Firefox + Adblock Plus 환경에서 문제가 발생하는것 같네요.
Chrome + Adblock plus/ublock/ Firefox + ublock은 문제가 없고요.

원인 파악후 추가적으로 코멘트 달겠습니다,

**Comment by ajkj** [comment]
v1.1.3에서 처리하였습니다.

해당 이슈는 fuckadblock의 문제 같으나, 일단은 `<script src="https://example.com?mid=fake ... >` 방식으로 처리하여 정상적으로 작동하도록 했습니다.

http://bit.ly/1QI4Tur#https://github.com/sitexw/FuckAdBlock/issues/22

**Comment by ajkj** [comment]
https://github.com/ajkj/xe-no_adblock_addon/releases

**Comment by ajkj** [comment]
문제가 생기면 다시 이슈를 열어주시면 감사하겠습니다.

**Comment by widz4rd** [comment]
고생하셨습니다 ;)*

확인 결과 정상적으로 작동하네요. ^^**

**Comment by Syangki** [comment]
윈도우8.1 파이어폭스 최신버전. adblockplus 사용하고있습니다. 감지를 못하는것 같네용
