### ISSUE TITLE
파폭에서 감지안됨 + 크롬에서 여전히차단됨.

### ISSUE THREAD

**Issue by Syangki** [ajkj/xe-no_adblock_addon#2]
윈도우8.1 파이어폭스 최신버전 + adblockplus 쓰고있는데 감지가 안되는것 같네요
전에 이슈를 제가 다시 오픈할수가 없어서 새로남깁니다.

크롬에서 adBlock을 쓰면 감지는 되지만 광고가 안나오네요

**Comment by ajkj** [comment]
- 증상 재현이 되지 않습니다. 애드온 v1.1.3 + 파이어폭스 38 + adblock plus 에서 정상적으로 감지가 되고 있습니다. adblock이 일시 중지되거나, 사이트 예외처리 하면 정상적으로 광고가 나오네요. 문제가 발생하신경우 정확한 증상재현 환경을 알려주시면 좋겠습니다.

- 그리고 adblock 으로 감지가 될 경우 광고가 나오지 않는것은 정상입니다. 애드온의 역할은 광고차단프로그램의 동작을 차단하는 것이 아니라, 광고차단프로램의 동작 여부를 **검출** 하는 것이에요. 검출한 뒤에  모달창을 띄워 접속을 제한하거나, 아니면, 통계처리만 하는 등의 행동은 이용자분이 설정/결정 하시는 거에요. (기술적 문제로 브라우져상에서 돌아가는 광고차단프로그램을 차단하기는 힘들것 같네요)

**Comment by Syangki** [comment]
애드온 1.1.3 + 파폭 38.0.5 + Adblock Plus 2.6.9.1 - signed 입니다. 모달창 안내를 하고있는데 모달창이 안뜨네요 혹시나라도 저만의 문제라면 이슈닫겠습니다 ㅠ

**Comment by ajkj** [comment]
증상재현이 되지 않네요. Adblock Plus 버젼은 2.6.9.1 - signed 으로 동일합니다.

**Comment by widz4rd** [comment]
이메일로 뭔가 오길래 저 또한 답을 달아봅니다.
애드온 1.1.3 + 파이어폭스 38.0.5 최신 + Adbloc Plus 
광고 차단하고 접속하는 경우 팝업 잘 뜨고, 광고 해제 후 재접속 버튼누르면 팝업 뜨지 않습니다.

해당 문제 해결에 있어 도움이 되었으면 좋겠습니다.
